module.exports = {
  NEWS_API_KEY: process.env.NEWS_API_KEY,
  WEATHER_API_KEY: process.env.WEATHER_API_KEY,
  MARKET_API_KEY: process.env.MARKET_API_KEY,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_WHATSAPP_NUMBER: process.env.TWILIO_WHATSAPP_NUMBER
};

